// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TeineTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  Reporter rp;
  
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    rp = new Reporter();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void teine() throws Exception {
    // Test name: Teine
    // Step # | name | target | value
	rp.addSimple("<h1>teine test</h1>");
	
	try {
    
	// 1 | open | /index.php | 
	rp.add("// 1 | open | /index.php | ");
    driver.get("http://automationpractice.com/index.php");
    System.out.println("// 1 | open | /index.php | ");
    
    // 2 | setWindowSize | 1472x1040 | 
    rp.add("// 2 | setWindowSize | 1400x1000 | ");
    driver.manage().window().setSize(new Dimension(1472, 1040));
    System.out.println("// 2 | setWindowSize | 1400x1000 | ");
    
    //Thread.sleep(3000);
    
    // 3 | click | css=.sfHover > a | 
    rp.add("// 3 | click | T-shirts | ");
    driver.findElement(By.cssSelector("#block_top_menu > ul > li:nth-child(3)")).click();
    System.out.println("// 3 | click | T-shirts | ");
    
    //Thread.sleep(5000);
    
    // 4 | click | css=.lnk_view > span | 
    rp.add("// 4 | click | css=.lnk_view > span | ");
    driver.findElement(By.className("product_img_link")).click();
    System.out.println("// 4 | click | product picture | ");
    
    Thread.sleep(3000);
    
    // 5 | click | css=.button-medium > span | 
    rp.add("// 5 | click | css=.button-medium > span | ");
    driver.findElement(By.xpath("//h1[text()='Faded Short Sleeve T-shirts']"));
    System.out.println("// 5 | find | Faded Short Sleeve T-shirts | ");

    // 6 | click | css=.product_attributes | 
    rp.add("// 6 | click | css=.product_attributes | ");
    driver.findElement(By.xpath("//span[text()='$16.51']"));
    System.out.println("// 6 | find | $16.51 | ");
  
    //Thread.sleep(5000);
    
    // 7 | type | id=quantity_wanted | 2
    rp.add("// 7 | type | id=quantity_wanted | 2");
    driver.findElement(By.id("quantity_wanted")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("quantity_wanted")).sendKeys("2");
    System.out.println("// 7 | type | quantity = 2 | ");

    // 8 | select | id=group_1 | label=L
    rp.add("// 8 | select | id=group_1 | label=L");
    {
      WebElement dropdown = driver.findElement(By.id("group_1"));
      dropdown.findElement(By.xpath("//option[. = 'L']")).click();
    }
    System.out.println("// 8 | select | size = L");

    // 9 | click | id=color_14 | 
    rp.add("// 9 | click | id=color_14444 | ");
    driver.findElement(By.id("color_14444")).click();
    System.out.println("// 9 | click | color = blue | ");
    
    // 10 | click | css=.exclusive > span | 
    rp.add("// 10 | click | css=.exclusive > span | ");
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    System.out.println("// 10 | click | add to cart | ");
    /*
    Thread.sleep(3000);
    
    // 11 | click | css=h2:nth-child(2) | 
    rp.add("// 11 | click | css=h2:nth-child(2) | ");
    driver.findElement(By.cssSelector("#layer_cart > div.clearfix > div.layer_cart_cart.col-xs-12.col-md-6 > div.button-container > a > span")).click();
    System.out.println("// 11 | click | proceed to checkout | ");
    
    //Thread.sleep(3000);
    
    // 12 | click | css=.button-medium > span | 
    rp.add("// 12 | click | css=.button-medium > span | ");
    driver.findElement(By.xpath("//a[text()='Faded Short Sleeve T-shirts']"));
    System.out.println("// 12 | find | Faded Short Sleeve T-shirts | ");
    
    // 13 | click | css=tr > .first_item | 
    rp.add("// 13 | click | css=tr > .first_item | ");
    driver.findElement(By.xpath("//a[text()='Color : Blue, Size : L']"));
    System.out.println("// 13 | find | Color : Blue, Size : L | ");
    
    // 14 | click | css=tr > .item:nth-child(2) | 
    rp.add("// 14 | click | css=tr > .item:nth-child(2) | ");
    driver.findElement(By.xpath("//td[text()='$33.02']"));
    System.out.println("// 14 | find | $33.02 | ");
    
    // 15 | click | css=.standard-checkout > span | 
    rp.add("// 15 | click | css=.standard-checkout > span | ");
    driver.findElement(By.xpath("//span[text()='Proceed to checkout']"));
    System.out.println("// 15 | find | proceed to checkout | ");
    
    // 16 | click | css=.icon-trash | 
    rp.add("// 16 | click | css=.icon-trash | ");
    driver.findElement(By.className("icon-trash")).click();
    System.out.println("// 16 | click | delete product | ");
    
    // 17 | click | css=.standard-checkout > span | 
    rp.add("// 17 | click | css=.standard-checkout > span | ");
    driver.findElement(By.xpath("//p[text()='Your shopping cart is empty.']"));
    System.out.println("// 17 | find | Your shopping cart is empty. | ");
*/
    rp.add("<b><font style=\"color:green;\">!!! TEST PASSED !!!</font></b>");
    
	}
	  catch(Exception e){
		  e.printStackTrace();
		  rp.add("<p style=\"color:red;\">" + e.getMessage() + "</p>");
	  }
    
  }
}
